/// Static English POS dictionary covering high-frequency words.
/// Format: (word_lowercase, [possible_pos_tags])
///
/// Penn Treebank tagset with LT extensions:
/// CC CD DT EX FW IN JJ JJR JJS LS MD NN NNP NNPS NNS PDT POS PRP PRP$
/// RB RBR RBS RP SYM TO UH VB VBD VBG VBN VBP VBZ WDT WP WP$ WRB
/// LT extensions: NN:U NN:UN ORD PCT RB_SENT SENT_START SENT_END UNKNOWN
pub static ENGLISH_POS_DICT: &[(&str, &[&str])] = &[
    // === Determiners (DT) ===
    ("the", &["DT"]),
    ("a", &["DT", "NN"]),
    ("an", &["DT"]),
    ("this", &["DT", "NN", "RB"]),
    ("that", &["DT", "IN", "WDT", "NN"]),
    ("these", &["DT"]),
    ("those", &["DT"]),
    ("every", &["DT"]),
    ("each", &["DT"]),
    ("all", &["DT", "PDT", "RB"]),
    ("both", &["DT", "CC"]),
    ("some", &["DT"]),
    ("any", &["DT"]),
    ("no", &["DT", "RB"]),
    ("either", &["DT", "CC"]),
    ("neither", &["DT", "CC"]),
    ("another", &["DT"]),
    ("such", &["DT", "PDT", "JJ"]),
    ("what", &["DT", "WP"]),
    ("which", &["DT", "WDT"]),
    ("whatever", &["DT", "WDT"]),
    ("whichever", &["DT", "WDT"]),
    ("quite", &["PDT", "RB"]),

    // === Prepositions (IN) ===
    ("of", &["IN"]),
    ("in", &["IN", "RB", "RP"]),
    ("to", &["TO", "IN"]),
    ("for", &["IN", "CC"]),
    ("with", &["IN"]),
    ("on", &["IN", "RB", "RP"]),
    ("at", &["IN"]),
    ("from", &["IN"]),
    ("by", &["IN", "RP"]),
    ("about", &["IN", "RB", "RP"]),
    ("as", &["IN", "RB", "CC"]),
    ("into", &["IN"]),
    ("through", &["IN", "RB", "RP"]),
    ("during", &["IN"]),
    ("before", &["IN", "RB", "RP"]),
    ("after", &["IN", "RB", "RP"]),
    ("above", &["IN", "RB", "JJ", "RP"]),
    ("below", &["IN", "RB"]),
    ("between", &["IN"]),
    ("under", &["IN", "RB"]),
    ("over", &["IN", "RB", "JJ", "RP"]),
    ("without", &["IN"]),
    ("within", &["IN"]),
    ("along", &["IN", "RB", "RP"]),
    ("against", &["IN"]),
    ("among", &["IN"]),
    ("throughout", &["IN"]),
    ("despite", &["IN"]),
    ("toward", &["IN"]),
    ("towards", &["IN"]),
    ("upon", &["IN"]),
    ("around", &["IN", "RB", "RP"]),
    ("beyond", &["IN", "RB"]),
    ("until", &["IN", "CC"]),
    ("since", &["IN", "RB", "CC"]),
    ("across", &["IN", "RB"]),
    ("behind", &["IN", "RB"]),
    ("beside", &["IN"]),
    ("besides", &["IN", "RB", "CC"]),
    ("beneath", &["IN", "RB"]),
    ("onto", &["IN"]),
    ("unlike", &["IN", "JJ"]),
    ("off", &["IN", "RB", "RP"]),
    ("up", &["IN", "RB", "RP"]),
    ("down", &["IN", "RB", "RP"]),
    ("out", &["IN", "RB", "RP"]),
    ("past", &["IN", "JJ", "NN", "RB"]),
    ("near", &["IN", "JJ", "RB"]),
    ("outside", &["IN", "JJ", "NN", "RB"]),
    ("inside", &["IN", "JJ", "NN", "RB"]),
    ("except", &["IN", "CC"]),
    ("via", &["IN"]),
    ("per", &["IN"]),
    ("than", &["IN"]),
    ("like", &["IN", "VB", "NN", "JJ"]),

    // === Coordinating Conjunctions (CC) ===
    ("and", &["CC"]),
    ("but", &["CC", "RB"]),
    ("or", &["CC"]),
    ("nor", &["CC"]),
    ("so", &["CC", "RB"]),
    ("yet", &["CC", "RB"]),

    // === Modals (MD) ===
    ("can", &["MD"]),
    ("could", &["MD"]),
    ("will", &["MD", "NN"]),
    ("would", &["MD"]),
    ("shall", &["MD"]),
    ("should", &["MD"]),
    ("may", &["MD", "NN"]),
    ("might", &["MD"]),
    ("must", &["MD"]),
    ("ought", &["MD"]),

    // === Personal Pronouns (PRP) ===
    ("i", &["PRP"]),
    ("you", &["PRP"]),
    ("he", &["PRP"]),
    ("she", &["PRP"]),
    ("it", &["PRP"]),
    ("we", &["PRP"]),
    ("they", &["PRP"]),
    ("me", &["PRP"]),
    ("him", &["PRP"]),
    ("her", &["PRP", "PRP$"]),
    ("us", &["PRP"]),
    ("them", &["PRP"]),

    // === Possessive Pronouns (PRP$) ===
    ("my", &["PRP$"]),
    ("your", &["PRP$"]),
    ("his", &["PRP$", "PRP"]),
    ("its", &["PRP$"]),
    ("our", &["PRP$"]),
    ("their", &["PRP$"]),
    ("mine", &["PRP$"]),
    ("yours", &["PRP$"]),
    ("hers", &["PRP$"]),
    ("ours", &["PRP$"]),
    ("theirs", &["PRP$"]),

    // === Wh-words ===
    ("who", &["WP"]),
    ("whom", &["WP"]),
    ("whose", &["WP$"]),
    ("how", &["WRB"]),
    ("where", &["WRB", "NN"]),
    ("when", &["WRB", "IN", "CC"]),
    ("why", &["WRB"]),

    // === Indefinite pronouns ===
    ("nothing", &["NN:U", "RB"]),
    ("nobody", &["NN:U"]),
    ("nowhere", &["NN:U", "RB"]),
    ("anything", &["NN:U"]),
    ("anybody", &["NN:U"]),
    ("anywhere", &["JJ", "NN", "RB"]),
    ("everything", &["NN:U", "PRP"]),
    ("everybody", &["NN:U", "PRP"]),
    ("everywhere", &["RB"]),
    ("something", &["NN:U"]),
    ("somebody", &["NN:U"]),
    ("someone", &["NN:U"]),
    ("anyone", &["NN:U"]),
    ("everyone", &["NN:U"]),
    ("no one", &["NN:U"]),
    ("none", &["NN:U", "JJ"]),

    // === Existential (EX) ===
    ("there", &["EX", "RB"]),

    // === Particles (RP) ===
    ("away", &["RB", "RP"]),
    ("back", &["RB", "RP", "NN", "JJ", "VB"]),
    ("ahead", &["RB"]),
    ("apart", &["RB"]),
    ("aside", &["RB"]),

    // === Common Adverbs (RB) ===
    ("not", &["RB"]),
    ("very", &["RB"]),
    ("also", &["RB"]),
    ("just", &["RB"]),
    ("now", &["RB", "NN"]),
    ("then", &["RB", "NN"]),
    ("here", &["RB"]),
    ("always", &["RB"]),
    ("never", &["RB"]),
    ("often", &["RB"]),
    ("still", &["RB", "JJ", "VB"]),
    ("already", &["RB"]),
    ("even", &["RB", "JJ"]),
    ("almost", &["RB"]),
    ("only", &["RB", "JJ"]),
    ("really", &["RB"]),
    ("quite", &["RB", "PDT"]),
    ("soon", &["RB"]),
    ("perhaps", &["RB"]),
    ("maybe", &["RB"]),
    ("certainly", &["RB"]),
    ("probably", &["RB"]),
    ("usually", &["RB"]),
    ("sometimes", &["RB"]),
    ("generally", &["RB"]),
    ("actually", &["RB"]),
    ("simply", &["RB"]),
    ("clearly", &["RB"]),
    ("especially", &["RB"]),
    ("particularly", &["RB"]),
    ("exactly", &["RB"]),
    ("completely", &["RB"]),
    ("immediately", &["RB"]),
    ("finally", &["RB"]),
    ("recently", &["RB"]),
    ("currently", &["RB"]),
    ("eventually", &["RB"]),
    ("previously", &["RB"]),
    ("obviously", &["RB"]),
    ("definitely", &["RB"]),
    ("apparently", &["RB"]),
    ("frequently", &["RB"]),
    ("increasingly", &["RB"]),
    ("significantly", &["RB"]),
    ("primarily", &["RB"]),
    ("largely", &["RB"]),
    ("relatively", &["RB"]),
    ("basically", &["RB"]),
    ("essentially", &["RB"]),
    ("typically", &["RB"]),
    ("naturally", &["RB"]),
    ("normally", &["RB"]),
    ("extremely", &["RB"]),
    ("absolutely", &["RB"]),
    ("seriously", &["RB"]),
    ("suddenly", &["RB"]),
    ("directly", &["RB"]),
    ("exactly", &["RB"]),
    ("hardly", &["RB"]),
    ("merely", &["RB"]),
    ("mostly", &["RB"]),
    ("nearly", &["RB"]),
    ("particularly", &["RB"]),
    ("perfectly", &["RB"]),
    ("possibly", &["RB"]),
    ("precisely", &["RB"]),
    ("pretty", &["RB", "JJ", "RB"]),
    ("purely", &["RB"]),
    ("rarely", &["RB"]),
    ("rather", &["RB"]),
    ("roughly", &["RB"]),
    ("slightly", &["RB"]),
    ("somewhat", &["RB"]),
    ("somewhere", &["RB"]),
    ("strongly", &["RB"]),
    ("suddenly", &["RB"]),
    ("sufficiently", &["RB"]),
    ("surely", &["RB"]),
    ("too", &["RB"]),
    ("totally", &["RB"]),
    ("truly", &["RB"]),
    ("usually", &["RB"]),
    ("virtually", &["RB"]),
    ("well", &["RB", "NN", "JJ", "UH", "VB"]),
    ("worse", &["RBR", "JJR"]),
    ("worst", &["RBS", "JJS", "NN"]),
    ("else", &["RB", "JJ"]),
    ("elsewhere", &["RB"]),
    ("forever", &["RB"]),
    ("forward", &["RB", "JJ"]),
    ("further", &["RBR", "RB", "JJR", "VB"]),
    ("furthermore", &["RB"]),
    ("however", &["RB", "WRB"]),
    ("if", &["IN"]),
    ("because", &["IN"]),
    ("although", &["IN"]),
    ("though", &["IN"]),
    ("unless", &["IN"]),
    ("whether", &["IN"]),
    ("whenever", &["WRB", "IN"]),
    ("wherever", &["WRB", "IN"]),
    ("while", &["IN", "NN", "VB", "VBP"]),
    ("until", &["IN", "CC"]),
    ("whereas", &["IN", "CC"]),
    ("once", &["IN", "RB", "CD"]),
    ("as", &["IN", "RB", "CC"]),
    ("when", &["WRB", "IN", "CC"]),
    ("where", &["WRB", "IN"]),
    ("after", &["IN", "RB", "RP"]),
    ("before", &["IN", "RB", "RP"]),
    ("instead", &["RB"]),
    ("later", &["RB", "JJ"]),
    ("least", &["RBS", "JJS", "NN"]),
    ("less", &["RBR", "JJR", "NN"]),
    ("more", &["RBR", "JJR", "NN"]),
    ("most", &["RBS", "JJS", "NN"]),
    ("much", &["RB", "NN", "JJ"]),
    ("once", &["RB", "NN", "CD"]),
    ("otherwise", &["RB"]),
    ("rather", &["RB"]),
    ("regardless", &["RB"]),
    ("therefore", &["RB"]),
    ("thus", &["RB"]),
    ("together", &["RB"]),
    ("twice", &["RB", "CD"]),
    ("ever", &["RB"]),
    ("again", &["RB"]),
    ("anyway", &["RB"]),
    ("anymore", &["RB"]),

    // === Be verb ===
    ("be", &["VB"]),
    ("am", &["VBP"]),
    ("is", &["VBZ"]),
    ("are", &["VBP"]),
    ("was", &["VBD"]),
    ("were", &["VBD"]),
    ("been", &["VBN"]),
    ("being", &["VBG", "NN"]),

    // === Have verb ===
    ("have", &["VB", "VBP", "NN"]),
    ("has", &["VBZ"]),
    ("had", &["VBD", "VBN"]),
    ("having", &["VBG"]),

    // === Do verb ===
    ("do", &["VB", "VBP"]),
    ("does", &["VBZ"]),
    ("did", &["VBD"]),
    ("done", &["VBN", "JJ"]),
    ("doing", &["VBG"]),

    // === Common Verbs (VB) base forms ===
    ("say", &["VB", "NN"]),
    ("get", &["VB", "NN"]),
    ("make", &["VB", "NN"]),
    ("go", &["VB", "NN"]),
    ("know", &["VB"]),
    ("take", &["VB", "NN"]),
    ("see", &["VB"]),
    ("come", &["VB"]),
    ("think", &["VB", "NN"]),
    ("look", &["VB", "NN"]),
    ("want", &["VB"]),
    ("give", &["VB"]),
    ("use", &["VB", "NN"]),
    ("find", &["VB", "NN"]),
    ("tell", &["VB"]),
    ("ask", &["VB"]),
    ("work", &["VB", "NN"]),
    ("seem", &["VB"]),
    ("feel", &["VB"]),
    ("try", &["VB", "NN"]),
    ("leave", &["VB", "NN"]),
    ("call", &["VB", "NN"]),
    ("keep", &["VB"]),
    ("let", &["VB"]),
    ("begin", &["VB"]),
    ("show", &["VB", "NN"]),
    ("hear", &["VB"]),
    ("play", &["VB", "NN"]),
    ("run", &["VB", "NN"]),
    ("move", &["VB", "NN"]),
    ("live", &["VB", "JJ"]),
    ("believe", &["VB"]),
    ("bring", &["VB"]),
    ("happen", &["VB"]),
    ("write", &["VB"]),
    ("provide", &["VB"]),
    ("sit", &["VB"]),
    ("stand", &["VB", "NN"]),
    ("lose", &["VB"]),
    ("pay", &["VB", "NN"]),
    ("meet", &["VB"]),
    ("include", &["VB"]),
    ("continue", &["VB"]),
    ("set", &["VB", "NN"]),
    ("learn", &["VB"]),
    ("change", &["VB", "NN"]),
    ("lead", &["VB", "NN"]),
    ("understand", &["VB"]),
    ("watch", &["VB", "NN"]),
    ("follow", &["VB"]),
    ("stop", &["VB", "NN"]),
    ("create", &["VB"]),
    ("speak", &["VB"]),
    ("read", &["VB", "NN"]),
    ("allow", &["VB"]),
    ("add", &["VB"]),
    ("spend", &["VB"]),
    ("grow", &["VB"]),
    ("open", &["VB", "JJ"]),
    ("walk", &["VB", "NN"]),
    ("win", &["VB", "NN"]),
    ("offer", &["VB", "NN"]),
    ("remember", &["VB"]),
    ("love", &["VB", "NN"]),
    ("consider", &["VB"]),
    ("appear", &["VB"]),
    ("buy", &["VB"]),
    ("wait", &["VB", "NN"]),
    ("serve", &["VB"]),
    ("die", &["VB"]),
    ("send", &["VB"]),
    ("expect", &["VB"]),
    ("build", &["VB", "NN"]),
    ("stay", &["VB", "NN"]),
    ("fall", &["VB", "NN"]),
    ("cut", &["VB", "NN"]),
    ("reach", &["VB", "NN"]),
    ("kill", &["VB"]),
    ("remain", &["VB"]),
    ("suggest", &["VB"]),
    ("raise", &["VB", "NN"]),
    ("pass", &["VB", "NN"]),
    ("sell", &["VB"]),
    ("require", &["VB"]),
    ("report", &["VB", "NN"]),
    ("decide", &["VB"]),
    ("pull", &["VB", "NN"]),
    ("put", &["VB"]),
    ("carry", &["VB"]),
    ("pick", &["VB", "NN"]),
    ("hold", &["VB", "NN"]),
    ("turn", &["VB", "NN"]),
    ("point", &["VB", "NN"]),
    ("cause", &["VB", "NN"]),
    ("receive", &["VB"]),
    ("agree", &["VB"]),
    ("support", &["VB", "NN"]),
    ("hit", &["VB", "NN"]),
    ("produce", &["VB"]),
    ("eat", &["VB"]),
    ("cover", &["VB", "NN"]),
    ("catch", &["VB"]),
    ("draw", &["VB", "NN"]),
    ("choose", &["VB"]),
    ("save", &["VB"]),
    ("fill", &["VB"]),
    ("break", &["VB", "NN"]),
    ("remain", &["VB"]),
    ("exist", &["VB"]),
    ("mean", &["VB", "JJ"]),
    ("start", &["VB", "NN"]),
    ("help", &["VB", "NN"]),
    ("talk", &["VB", "NN"]),
    ("turn", &["VB", "NN"]),
    ("need", &["VB", "NN"]),
    ("become", &["VB"]),
    ("leave", &["VB", "NN"]),
    ("put", &["VB"]),
    ("end", &["VB", "NN"]),
    ("meet", &["VB", "NN"]),
    ("carry", &["VB", "NN"]),
    ("pick", &["VB", "NN"]),
    ("produce", &["VB", "NN"]),
    ("eat", &["VB"]),
    ("teach", &["VB"]),
    ("wear", &["VB"]),
    ("rise", &["VB", "NN"]),
    ("drive", &["VB", "NN"]),
    ("develop", &["VB"]),
    ("die", &["VB"]),
    ("contain", &["VB"]),
    ("involve", &["VB"]),
    ("apply", &["VB"]),
    ("measure", &["VB", "NN"]),
    ("describe", &["VB"]),
    ("present", &["VB", "NN", "JJ"]),
    ("manage", &["VB"]),
    ("affect", &["VB"]),
    ("form", &["VB", "NN"]),
    ("face", &["VB", "NN"]),
    ("face", &["VB", "NN"]),
    ("handle", &["VB", "NN"]),
    ("express", &["VB"]),
    ("handle", &["VB", "NN"]),
    ("claim", &["VB", "NN"]),
    ("base", &["VB", "NN", "JJ"]),
    ("serve", &["VB"]),
    ("accept", &["VB"]),
    ("enjoy", &["VB"]),
    ("achieve", &["VB"]),
    ("contain", &["VB"]),
    ("assume", &["VB"]),
    ("avoid", &["VB"]),
    ("improve", &["VB"]),
    ("explain", &["VB"]),
    ("reveal", &["VB"]),
    ("announce", &["VB"]),
    ("indicate", &["VB"]),
    ("maintain", &["VB"]),
    ("increase", &["VB", "NN"]),
    ("reduce", &["VB"]),
    ("establish", &["VB"]),
    ("prepare", &["VB"]),
    ("replace", &["VB"]),
    ("remove", &["VB"]),
    ("ensure", &["VB"]),
    ("represent", &["VB"]),
    ("protect", &["VB"]),
    ("perform", &["VB"]),
    ("publish", &["VB"]),
    ("identify", &["VB"]),
    ("examine", &["VB"]),
    ("obtain", &["VB"]),
    ("determine", &["VB"]),
    ("suggest", &["VB"]),
    ("demonstrate", &["VB"]),
    ("occur", &["VB"]),
    ("encourage", &["VB"]),
    ("compare", &["VB"]),
    ("provide", &["VB"]),
    ("consider", &["VB"]),
    ("approach", &["VB", "NN"]),
    ("emerge", &["VB"]),
    ("propose", &["VB"]),
    ("promote", &["VB"]),
    ("conclude", &["VB"]),
    ("demand", &["VB", "NN"]),
    ("observe", &["VB"]),
    ("investigate", &["VB"]),
    ("resolve", &["VB"]),
    ("contribute", &["VB"]),
    ("predict", &["VB"]),
    ("generate", &["VB"]),
    ("acquire", &["VB"]),
    ("supply", &["VB", "NN"]),
    ("employ", &["VB"]),
    ("implement", &["VB"]),
    ("deliver", &["VB"]),
    ("assess", &["VB"]),
    ("analyze", &["VB"]),
    ("pursue", &["VB"]),
    ("explore", &["VB"]),
    ("engage", &["VB"]),
    ("adopt", &["VB"]),
    ("address", &["VB", "NN"]),
    ("acknowledge", &["VB"]),
    ("illustrate", &["VB"]),
    ("transfer", &["VB", "NN"]),
    ("recommend", &["VB"]),
    ("negotiate", &["VB"]),

    // === Common verbs - 3rd person singular (VBZ) ===
    ("says", &["VBZ", "NNS"]),
    ("gets", &["VBZ", "NNS"]),
    ("makes", &["VBZ", "NNS"]),
    ("goes", &["VBZ"]),
    ("knows", &["VBZ"]),
    ("takes", &["VBZ", "NNS"]),
    ("sees", &["VBZ"]),
    ("comes", &["VBZ", "NNS"]),
    ("thinks", &["VBZ", "NNS"]),
    ("looks", &["VBZ", "NNS"]),
    ("wants", &["VBZ", "NNS"]),
    ("gives", &["VBZ", "NNS"]),
    ("uses", &["VBZ", "NNS"]),
    ("finds", &["VBZ", "NNS"]),
    ("tells", &["VBZ", "NNS"]),
    ("asks", &["VBZ", "NNS"]),
    ("works", &["VBZ", "NNS"]),
    ("seems", &["VBZ"]),
    ("feels", &["VBZ"]),
    ("tries", &["VBZ", "NNS"]),
    ("leaves", &["VBZ", "NNS"]),
    ("calls", &["VBZ", "NNS"]),
    ("keeps", &["VBZ", "NNS"]),
    ("begins", &["VBZ"]),
    ("shows", &["VBZ", "NNS"]),
    ("hears", &["VBZ"]),
    ("plays", &["VBZ", "NNS"]),
    ("runs", &["VBZ", "NNS"]),
    ("moves", &["VBZ", "NNS"]),
    ("lives", &["VBZ", "NNS"]),
    ("believes", &["VBZ"]),
    ("brings", &["VBZ", "NNS"]),
    ("happens", &["VBZ"]),
    ("writes", &["VBZ", "NNS"]),
    ("provides", &["VBZ"]),
    ("sits", &["VBZ", "NNS"]),
    ("stands", &["VBZ", "NNS"]),
    ("loses", &["VBZ", "NNS"]),
    ("pays", &["VBZ", "NNS"]),
    ("meets", &["VBZ", "NNS"]),
    ("includes", &["VBZ"]),
    ("continues", &["VBZ"]),
    ("sets", &["VBZ", "NNS"]),
    ("learns", &["VBZ"]),
    ("changes", &["VBZ", "NNS"]),
    ("leads", &["VBZ", "NNS"]),
    ("understands", &["VBZ"]),
    ("watches", &["VBZ", "NNS"]),
    ("follows", &["VBZ"]),
    ("stops", &["VBZ", "NNS"]),
    ("creates", &["VBZ"]),
    ("speaks", &["VBZ"]),
    ("reads", &["VBZ", "NNS"]),
    ("allows", &["VBZ"]),
    ("adds", &["VBZ"]),
    ("spends", &["VBZ"]),
    ("grows", &["VBZ"]),
    ("opens", &["VBZ"]),
    ("walks", &["VBZ", "NNS"]),
    ("wins", &["VBZ", "NNS"]),
    ("offers", &["VBZ", "NNS"]),
    ("remembers", &["VBZ"]),
    ("loves", &["VBZ", "NNS"]),
    ("considers", &["VBZ"]),
    ("appears", &["VBZ"]),
    ("buys", &["VBZ"]),
    ("waits", &["VBZ", "NNS"]),
    ("serves", &["VBZ"]),
    ("dies", &["VBZ", "NNS"]),
    ("sends", &["VBZ", "NNS"]),
    ("expects", &["VBZ"]),
    ("builds", &["VBZ", "NNS"]),
    ("stays", &["VBZ", "NNS"]),
    ("falls", &["VBZ", "NNS"]),
    ("cuts", &["VBZ", "NNS"]),
    ("reaches", &["VBZ", "NNS"]),
    ("kills", &["VBZ", "NNS"]),
    ("remains", &["VBZ"]),
    ("suggests", &["VBZ"]),
    ("raises", &["VBZ", "NNS"]),
    ("passes", &["VBZ", "NNS"]),
    ("sells", &["VBZ", "NNS"]),
    ("requires", &["VBZ"]),
    ("reports", &["VBZ", "NNS"]),
    ("decides", &["VBZ"]),
    ("pulls", &["VBZ", "NNS"]),
    ("starts", &["VBZ", "NNS"]),
    ("helps", &["VBZ", "NNS"]),
    ("talks", &["VBZ", "NNS"]),
    ("turns", &["VBZ", "NNS"]),
    ("needs", &["VBZ", "NNS"]),
    ("becomes", &["VBZ"]),
    ("means", &["VBZ", "NNS"]),
    ("ends", &["VBZ", "NNS"]),
    ("holds", &["VBZ", "NNS"]),
    ("carries", &["VBZ", "NNS"]),
    ("produces", &["VBZ"]),
    ("eats", &["VBZ"]),
    ("teaches", &["VBZ", "NNS"]),
    ("wears", &["VBZ"]),
    ("rises", &["VBZ", "NNS"]),
    ("drives", &["VBZ", "NNS"]),
    ("develops", &["VBZ"]),
    ("involves", &["VBZ"]),
    ("applies", &["VBZ"]),
    ("describes", &["VBZ"]),
    ("presents", &["VBZ", "NNS"]),
    ("manages", &["VBZ", "NNS"]),
    ("affects", &["VBZ", "NNS"]),
    ("forms", &["VBZ", "NNS"]),
    ("faces", &["VBZ", "NNS"]),
    ("claims", &["VBZ", "NNS"]),
    ("accepts", &["VBZ"]),
    ("enjoys", &["VBZ"]),
    ("achieves", &["VBZ"]),
    ("assumes", &["VBZ"]),
    ("avoids", &["VBZ"]),
    ("improves", &["VBZ"]),
    ("explains", &["VBZ"]),
    ("reveals", &["VBZ"]),
    ("announces", &["VBZ"]),
    ("indicates", &["VBZ"]),
    ("maintains", &["VBZ"]),
    ("increases", &["VBZ", "NNS"]),
    ("reduces", &["VBZ"]),
    ("establishes", &["VBZ"]),
    ("prepares", &["VBZ"]),
    ("replaces", &["VBZ"]),
    ("removes", &["VBZ"]),
    ("ensures", &["VBZ"]),
    ("represents", &["VBZ"]),
    ("protects", &["VBZ"]),
    ("performs", &["VBZ"]),
    ("publishes", &["VBZ"]),
    ("identifies", &["VBZ"]),
    ("examines", &["VBZ"]),
    ("obtains", &["VBZ"]),
    ("determines", &["VBZ"]),
    ("demonstrates", &["VBZ"]),
    ("occurs", &["VBZ"]),
    ("encourages", &["VBZ"]),
    ("compares", &["VBZ"]),
    ("approaches", &["VBZ", "NNS"]),
    ("emerges", &["VBZ"]),
    ("proposes", &["VBZ"]),
    ("promotes", &["VBZ"]),
    ("concludes", &["VBZ"]),
    ("demands", &["VBZ", "NNS"]),
    ("observes", &["VBZ"]),
    ("investigates", &["VBZ"]),
    ("resolves", &["VBZ"]),
    ("contributes", &["VBZ"]),
    ("predicts", &["VBZ"]),
    ("generates", &["VBZ"]),
    ("acquires", &["VBZ"]),
    ("supplies", &["VBZ", "NNS"]),
    ("employs", &["VBZ"]),
    ("implements", &["VBZ"]),
    ("delivers", &["VBZ"]),
    ("assesses", &["VBZ"]),
    ("analyzes", &["VBZ"]),

    // === Common verbs - past tense (VBD) ===
    ("said", &["VBD"]),
    ("got", &["VBD"]),
    ("made", &["VBD", "VBN", "JJ"]),
    ("went", &["VBD"]),
    ("knew", &["VBD"]),
    ("took", &["VBD"]),
    ("saw", &["VBD"]),
    ("came", &["VBD"]),
    ("thought", &["VBD", "NN"]),
    ("looked", &["VBD", "VBN"]),
    ("wanted", &["VBD", "VBN"]),
    ("gave", &["VBD"]),
    ("used", &["VBD", "VBN", "JJ"]),
    ("found", &["VBD", "VBN"]),
    ("told", &["VBD", "VBN"]),
    ("asked", &["VBD", "VBN"]),
    ("worked", &["VBD", "VBN"]),
    ("seemed", &["VBD"]),
    ("felt", &["VBD", "VBN"]),
    ("tried", &["VBD", "VBN"]),
    ("left", &["VBD", "VBN", "JJ"]),
    ("called", &["VBD", "VBN"]),
    ("kept", &["VBD", "VBN"]),
    ("began", &["VBD"]),
    ("showed", &["VBD"]),
    ("heard", &["VBD", "VBN"]),
    ("played", &["VBD", "VBN"]),
    ("ran", &["VBD"]),
    ("moved", &["VBD", "VBN"]),
    ("lived", &["VBD", "VBN"]),
    ("believed", &["VBD", "VBN"]),
    ("brought", &["VBD", "VBN"]),
    ("happened", &["VBD"]),
    ("wrote", &["VBD"]),
    ("provided", &["VBD", "VBN"]),
    ("sat", &["VBD"]),
    ("stood", &["VBD"]),
    ("lost", &["VBD", "VBN", "JJ"]),
    ("paid", &["VBD", "VBN"]),
    ("met", &["VBD", "VBN"]),
    ("included", &["VBD", "VBN"]),
    ("continued", &["VBD", "VBN"]),
    ("set", &["VBD", "VBN"]),
    ("learned", &["VBD", "VBN"]),
    ("changed", &["VBD", "VBN"]),
    ("led", &["VBD", "VBN"]),
    ("understood", &["VBD", "VBN"]),
    ("watched", &["VBD", "VBN"]),
    ("followed", &["VBD", "VBN"]),
    ("stopped", &["VBD", "VBN"]),
    ("created", &["VBD", "VBN"]),
    ("spoke", &["VBD"]),
    ("read", &["VBD", "VBN"]),
    ("allowed", &["VBD", "VBN"]),
    ("added", &["VBD", "VBN"]),
    ("spent", &["VBD", "VBN"]),
    ("grew", &["VBD"]),
    ("opened", &["VBD", "VBN"]),
    ("walked", &["VBD", "VBN"]),
    ("won", &["VBD", "VBN"]),
    ("offered", &["VBD", "VBN"]),
    ("remembered", &["VBD", "VBN"]),
    ("loved", &["VBD", "VBN"]),
    ("considered", &["VBD", "VBN"]),
    ("appeared", &["VBD"]),
    ("bought", &["VBD", "VBN"]),
    ("waited", &["VBD", "VBN"]),
    ("served", &["VBD", "VBN"]),
    ("died", &["VBD", "VBN"]),
    ("sent", &["VBD", "VBN"]),
    ("expected", &["VBD", "VBN"]),
    ("built", &["VBD", "VBN"]),
    ("stayed", &["VBD", "VBN"]),
    ("fell", &["VBD"]),
    ("cut", &["VBD", "VBN"]),
    ("reached", &["VBD", "VBN"]),
    ("killed", &["VBD", "VBN"]),
    ("remained", &["VBD"]),
    ("suggested", &["VBD", "VBN"]),
    ("raised", &["VBD", "VBN"]),
    ("passed", &["VBD", "VBN"]),
    ("sold", &["VBD", "VBN"]),
    ("required", &["VBD", "VBN"]),
    ("reported", &["VBD", "VBN"]),
    ("decided", &["VBD", "VBN"]),
    ("started", &["VBD", "VBN"]),
    ("helped", &["VBD", "VBN"]),
    ("talked", &["VBD", "VBN"]),
    ("turned", &["VBD", "VBN"]),
    ("needed", &["VBD", "VBN"]),
    ("became", &["VBD"]),
    ("meant", &["VBD", "VBN"]),
    ("ended", &["VBD", "VBN"]),
    ("held", &["VBD", "VBN"]),
    ("produced", &["VBD", "VBN"]),
    ("ate", &["VBD"]),
    ("taught", &["VBD", "VBN"]),
    ("wore", &["VBD"]),
    ("rose", &["VBD", "NN"]),
    ("drove", &["VBD"]),
    ("developed", &["VBD", "VBN"]),
    ("involved", &["VBD", "VBN"]),
    ("applied", &["VBD", "VBN"]),
    ("described", &["VBD", "VBN"]),
    ("presented", &["VBD", "VBN"]),
    ("managed", &["VBD", "VBN"]),
    ("affected", &["VBD", "VBN"]),
    ("formed", &["VBD", "VBN"]),
    ("faced", &["VBD", "VBN"]),
    ("claimed", &["VBD", "VBN"]),
    ("accepted", &["VBD", "VBN"]),
    ("enjoyed", &["VBD", "VBN"]),
    ("achieved", &["VBD", "VBN"]),
    ("assumed", &["VBD", "VBN"]),
    ("avoided", &["VBD", "VBN"]),
    ("improved", &["VBD", "VBN"]),
    ("explained", &["VBD", "VBN"]),
    ("revealed", &["VBD", "VBN"]),
    ("announced", &["VBD", "VBN"]),
    ("indicated", &["VBD", "VBN"]),
    ("maintained", &["VBD", "VBN"]),
    ("increased", &["VBD", "VBN"]),
    ("reduced", &["VBD", "VBN"]),
    ("established", &["VBD", "VBN"]),
    ("prepared", &["VBD", "VBN"]),
    ("replaced", &["VBD", "VBN"]),
    ("removed", &["VBD", "VBN"]),
    ("ensured", &["VBD", "VBN"]),
    ("represented", &["VBD", "VBN"]),
    ("protected", &["VBD", "VBN"]),
    ("performed", &["VBD", "VBN"]),
    ("published", &["VBD", "VBN"]),
    ("identified", &["VBD", "VBN"]),
    ("examined", &["VBD", "VBN"]),
    ("obtained", &["VBD", "VBN"]),
    ("determined", &["VBD", "VBN"]),
    ("demonstrated", &["VBD", "VBN"]),
    ("occurred", &["VBD"]),

    // === Common verbs - gerund/present participle (VBG) ===
    ("saying", &["VBG"]),
    ("getting", &["VBG"]),
    ("making", &["VBG", "NN"]),
    ("going", &["VBG", "NN"]),
    ("knowing", &["VBG", "NN"]),
    ("taking", &["VBG", "NN"]),
    ("seeing", &["VBG", "NN"]),
    ("coming", &["VBG", "NN"]),
    ("thinking", &["VBG", "NN"]),
    ("looking", &["VBG", "NN"]),
    ("wanting", &["VBG"]),
    ("giving", &["VBG", "NN"]),
    ("using", &["VBG", "NN"]),
    ("finding", &["VBG", "NN"]),
    ("telling", &["VBG"]),
    ("asking", &["VBG"]),
    ("working", &["VBG", "NN", "JJ"]),
    ("seeming", &["VBG"]),
    ("feeling", &["VBG", "NN"]),
    ("trying", &["VBG", "NN"]),
    ("leaving", &["VBG", "NN"]),
    ("calling", &["VBG", "NN"]),
    ("keeping", &["VBG"]),
    ("beginning", &["VBG", "NN"]),
    ("showing", &["VBG", "NN"]),
    ("hearing", &["VBG", "NN"]),
    ("playing", &["VBG", "NN"]),
    ("running", &["VBG", "NN", "JJ"]),
    ("moving", &["VBG", "JJ"]),
    ("living", &["VBG", "NN", "JJ"]),
    ("believing", &["VBG"]),
    ("bringing", &["VBG"]),
    ("happening", &["VBG", "NN"]),
    ("writing", &["VBG", "NN"]),
    ("providing", &["VBG"]),
    ("sitting", &["VBG", "NN"]),
    ("standing", &["VBG", "NN"]),
    ("losing", &["VBG", "NN"]),
    ("paying", &["VBG"]),
    ("meeting", &["VBG", "NN"]),
    ("including", &["VBG", "IN"]),
    ("continuing", &["VBG"]),
    ("setting", &["VBG", "NN"]),
    ("learning", &["VBG", "NN"]),
    ("changing", &["VBG", "NN"]),
    ("leading", &["VBG", "NN", "JJ"]),
    ("understanding", &["VBG", "NN"]),
    ("watching", &["VBG", "NN"]),
    ("following", &["VBG", "NN", "JJ"]),
    ("stopping", &["VBG", "NN"]),
    ("creating", &["VBG"]),
    ("speaking", &["VBG", "NN"]),
    ("reading", &["VBG", "NN"]),
    ("allowing", &["VBG"]),
    ("adding", &["VBG", "NN"]),
    ("spending", &["VBG"]),
    ("growing", &["VBG", "JJ"]),
    ("opening", &["VBG", "NN"]),
    ("walking", &["VBG", "NN"]),
    ("winning", &["VBG", "NN"]),
    ("offering", &["VBG", "NN"]),
    ("building", &["VBG", "NN"]),
    ("starting", &["VBG", "NN"]),
    ("helping", &["VBG"]),
    ("talking", &["VBG", "NN"]),
    ("turning", &["VBG", "NN"]),
    ("needing", &["VBG"]),
    ("becoming", &["VBG"]),
    ("meaning", &["VBG", "NN"]),
    ("ending", &["VBG", "NN"]),
    ("holding", &["VBG", "NN"]),
    ("carrying", &["VBG"]),
    ("producing", &["VBG"]),
    ("eating", &["VBG"]),
    ("teaching", &["VBG", "NN"]),
    ("wearing", &["VBG", "NN"]),
    ("rising", &["VBG", "NN"]),
    ("driving", &["VBG", "NN"]),
    ("developing", &["VBG", "JJ"]),
    ("involving", &["VBG"]),
    ("applying", &["VBG"]),
    ("describing", &["VBG"]),
    ("presenting", &["VBG"]),
    ("managing", &["VBG", "NN"]),
    ("affecting", &["VBG"]),
    ("forming", &["VBG"]),
    ("facing", &["VBG", "NN"]),
    ("claiming", &["VBG"]),
    ("accepting", &["VBG"]),
    ("enjoying", &["VBG"]),
    ("achieving", &["VBG"]),
    ("assuming", &["VBG"]),
    ("avoiding", &["VBG"]),
    ("improving", &["VBG"]),
    ("explaining", &["VBG"]),
    ("revealing", &["VBG"]),
    ("announcing", &["VBG"]),
    ("indicating", &["VBG"]),
    ("maintaining", &["VBG"]),
    ("increasing", &["VBG", "JJ"]),
    ("reducing", &["VBG"]),
    ("establishing", &["VBG"]),
    ("preparing", &["VBG"]),
    ("replacing", &["VBG"]),
    ("removing", &["VBG"]),
    ("ensuring", &["VBG"]),
    ("representing", &["VBG"]),
    ("protecting", &["VBG"]),
    ("performing", &["VBG"]),
    ("publishing", &["VBG"]),
    ("identifying", &["VBG"]),
    ("examining", &["VBG"]),
    ("obtaining", &["VBG"]),
    ("determining", &["VBG"]),
    ("demonstrating", &["VBG"]),
    ("occurring", &["VBG"]),
    ("encouraging", &["VBG"]),
    ("comparing", &["VBG"]),
    ("approaching", &["VBG"]),
    ("emerging", &["VBG"]),
    ("proposing", &["VBG"]),
    ("promoting", &["VBG"]),
    ("concluding", &["VBG"]),
    ("demanding", &["VBG", "JJ"]),
    ("observing", &["VBG"]),
    ("investigating", &["VBG"]),
    ("resolving", &["VBG"]),
    ("contributing", &["VBG"]),
    ("predicting", &["VBG"]),
    ("generating", &["VBG"]),

    // === Common verbs - past participle (VBN) ===
    ("been", &["VBN"]),
    ("given", &["VBN", "VBD", "JJ"]),
    ("taken", &["VBN", "VBD"]),
    ("seen", &["VBN", "VBD"]),
    ("known", &["VBN", "VBD", "JJ"]),
    ("gone", &["VBN", "VBD", "JJ"]),
    ("come", &["VBN", "VBD"]),
    ("done", &["VBN", "VBD", "JJ"]),
    ("had", &["VBN", "VBD"]),
    ("said", &["VBN", "VBD"]),
    ("told", &["VBN", "VBD"]),
    ("put", &["VBN", "VBD"]),
    ("set", &["VBN", "VBD"]),
    ("let", &["VBN", "VBD"]),
    ("kept", &["VBN", "VBD"]),
    ("left", &["VBN", "VBD", "JJ"]),
    ("thought", &["VBN", "VBD", "NN"]),
    ("found", &["VBN", "VBD"]),
    ("met", &["VBN", "VBD"]),
    ("run", &["VBN", "VBD", "NN", "VB"]),
    ("grown", &["VBN", "VBD"]),
    ("shown", &["VBN", "VBD"]),
    ("written", &["VBN", "VBD"]),
    ("spoken", &["VBN", "VBD"]),
    ("broken", &["VBN", "VBD", "JJ"]),
    ("chosen", &["VBN", "VBD"]),
    ("driven", &["VBN", "VBD"]),
    ("eaten", &["VBN", "VBD"]),
    ("fallen", &["VBN", "VBD"]),
    ("forgotten", &["VBN", "VBD"]),
    ("frozen", &["VBN", "VBD", "JJ"]),
    ("gotten", &["VBN", "VBD"]),
    ("hidden", &["VBN", "VBD", "JJ"]),
    ("ridden", &["VBN", "VBD"]),
    ("risen", &["VBN", "VBD"]),
    ("stolen", &["VBN", "VBD"]),
    ("sworn", &["VBN", "VBD"]),
    ("thrown", &["VBN", "VBD"]),
    ("worn", &["VBN", "VBD"]),
    ("begun", &["VBN"]),
    ("drunk", &["VBN", "VBD", "JJ"]),
    ("sung", &["VBN", "VBD"]),
    ("swum", &["VBN", "VBD"]),
    ("awoken", &["VBN"]),
    ("born", &["VBN", "JJ"]),

    // === Common Nouns (NN) ===
    ("time", &["NN", "VB"]),
    ("year", &["NN"]),
    ("people", &["NN", "NNS"]),
    ("way", &["NN"]),
    ("day", &["NN"]),
    ("man", &["NN"]),
    ("woman", &["NN"]),
    ("child", &["NN"]),
    ("world", &["NN"]),
    ("life", &["NN"]),
    ("hand", &["NN", "VB"]),
    ("part", &["NN"]),
    ("place", &["NN", "VB"]),
    ("case", &["NN"]),
    ("week", &["NN"]),
    ("company", &["NN"]),
    ("system", &["NN"]),
    ("program", &["NN"]),
    ("question", &["NN"]),
    ("government", &["NN"]),
    ("number", &["NN"]),
    ("night", &["NN"]),
    ("point", &["NN", "VB"]),
    ("home", &["NN", "RB"]),
    ("water", &["NN", "VB"]),
    ("room", &["NN"]),
    ("mother", &["NN"]),
    ("area", &["NN"]),
    ("money", &["NN"]),
    ("story", &["NN"]),
    ("fact", &["NN"]),
    ("month", &["NN"]),
    ("lot", &["NN"]),
    ("study", &["NN", "VB"]),
    ("book", &["NN", "VB"]),
    ("eye", &["NN"]),
    ("job", &["NN"]),
    ("word", &["NN"]),
    ("business", &["NN"]),
    ("issue", &["NN"]),
    ("side", &["NN"]),
    ("kind", &["NN"]),
    ("head", &["NN", "VB"]),
    ("house", &["NN"]),
    ("service", &["NN"]),
    ("friend", &["NN"]),
    ("father", &["NN"]),
    ("power", &["NN"]),
    ("hour", &["NN"]),
    ("game", &["NN"]),
    ("line", &["NN"]),
    ("end", &["NN", "VB"]),
    ("member", &["NN"]),
    ("law", &["NN"]),
    ("car", &["NN"]),
    ("city", &["NN"]),
    ("community", &["NN"]),
    ("name", &["NN", "VB"]),
    ("president", &["NN"]),
    ("team", &["NN"]),
    ("minute", &["NN"]),
    ("idea", &["NN"]),
    ("body", &["NN"]),
    ("information", &["NN"]),
    ("parent", &["NN"]),
    ("face", &["NN", "VB"]),
    ("level", &["NN"]),
    ("office", &["NN"]),
    ("door", &["NN"]),
    ("health", &["NN"]),
    ("person", &["NN"]),
    ("art", &["NN"]),
    ("war", &["NN"]),
    ("history", &["NN"]),
    ("party", &["NN"]),
    ("result", &["NN"]),
    ("morning", &["NN"]),
    ("reason", &["NN"]),
    ("research", &["NN"]),
    ("girl", &["NN"]),
    ("guy", &["NN"]),
    ("moment", &["NN"]),
    ("air", &["NN"]),
    ("teacher", &["NN"]),
    ("force", &["NN", "VB"]),
    ("education", &["NN"]),
    ("foot", &["NN"]),
    ("boy", &["NN"]),
    ("age", &["NN"]),
    ("policy", &["NN"]),
    ("process", &["NN"]),
    ("music", &["NN"]),
    ("market", &["NN"]),
    ("sense", &["NN"]),
    ("product", &["NN"]),
    ("effect", &["NN"]),
    ("class", &["NN"]),
    ("piece", &["NN"]),
    ("land", &["NN", "VB"]),
    ("experience", &["NN", "VB"]),
    ("rate", &["NN", "VB"]),
    ("role", &["NN"]),
    ("degree", &["NN"]),
    ("behaviour", &["NN"]),
    ("behavior", &["NN"]),
    ("centre", &["NN"]),
    ("center", &["NN"]),
    ("couple", &["NN"]),
    ("project", &["NN", "VB"]),
    ("space", &["NN"]),
    ("record", &["NN", "VB"]),
    ("technology", &["NN"]),
    ("stage", &["NN"]),
    ("figure", &["NN", "VB"]),
    ("table", &["NN"]),
    ("field", &["NN"]),
    ("term", &["NN"]),
    ("picture", &["NN"]),
    ("value", &["NN", "VB"]),
    ("size", &["NN"]),
    ("model", &["NN"]),
    ("source", &["NN"]),
    ("control", &["NN", "VB"]),
    ("light", &["NN", "VB", "JJ"]),
    ("group", &["NN"]),
    ("problem", &["NN"]),
    ("event", &["NN"]),
    ("situation", &["NN"]),
    ("activity", &["NN"]),
    ("society", &["NN"]),
    ("country", &["NN"]),
    ("evidence", &["NN"]),
    ("structure", &["NN", "VB"]),
    ("plan", &["NN", "VB"]),
    ("attention", &["NN"]),
    ("form", &["NN", "VB"]),
    ("practice", &["NN", "VB"]),
    ("view", &["NN", "VB"]),
    ("data", &["NN", "NNS"]),
    ("nation", &["NN"]),
    ("development", &["NN"]),
    ("family", &["NN"]),
    ("approach", &["NN", "VB"]),
    ("chance", &["NN"]),
    ("choice", &["NN"]),
    ("action", &["NN"]),
    ("response", &["NN"]),
    ("example", &["NN"]),
    ("road", &["NN"]),
    ("voice", &["NN"]),
    ("type", &["NN", "VB"]),
    ("material", &["NN", "JJ"]),
    ("feature", &["NN", "VB"]),
    ("wall", &["NN"]),
    ("floor", &["NN"]),
    ("cup", &["NN"]),
    ("hat", &["NN"]),
    ("phone", &["NN"]),
    ("student", &["NN"]),
    ("doctor", &["NN"]),
    ("professor", &["NN"]),
    ("paper", &["NN"]),
    ("test", &["NN", "VB"]),
    ("rule", &["NN", "VB"]),
    ("sentence", &["NN"]),
    ("word", &["NN"]),
    ("language", &["NN"]),
    ("text", &["NN"]),
    ("letter", &["NN"]),
    ("page", &["NN"]),
    ("chapter", &["NN"]),
    ("section", &["NN"]),
    ("title", &["NN"]),
    ("list", &["NN", "VB"]),
    ("pattern", &["NN"]),
    ("format", &["NN", "VB"]),
    ("file", &["NN", "VB"]),
    ("code", &["NN", "VB"]),
    ("error", &["NN"]),
    ("version", &["NN"]),
    ("method", &["NN"]),
    ("function", &["NN"]),
    ("number", &["NN", "VB"]),
    ("step", &["NN", "VB"]),
    ("base", &["NN", "VB", "JJ"]),
    ("condition", &["NN"]),
    ("task", &["NN"]),
    ("task", &["NN"]),
    ("effort", &["NN"]),
    ("knowledge", &["NN"]),
    ("training", &["NN"]),
    ("computer", &["NN"]),
    ("software", &["NN"]),
    ("network", &["NN"]),
    ("internet", &["NN"]),
    ("website", &["NN"]),
    ("machine", &["NN"]),
    ("engine", &["NN"]),
    ("tool", &["NN"]),
    ("device", &["NN"]),
    ("energy", &["NN"]),
    ("science", &["NN"]),
    ("analysis", &["NN"]),
    ("theory", &["NN"]),
    ("measure", &["NN", "VB"]),
    ("standard", &["NN", "JJ"]),
    ("test", &["NN", "VB"]),
    ("nature", &["NN"]),
    ("environment", &["NN"]),
    ("population", &["NN"]),
    ("century", &["NN"]),
    ("decade", &["NN"]),
    ("season", &["NN"]),
    ("summer", &["NN"]),
    ("winter", &["NN"]),
    ("spring", &["NN", "VB"]),
    ("autumn", &["NN"]),
    ("today", &["NN", "RB"]),
    ("tomorrow", &["NN", "RB"]),
    ("yesterday", &["NN", "RB"]),
    ("percent", &["NN"]),
    ("half", &["NN", "DT", "PDT"]),
    ("quarter", &["NN", "CD"]),

    // === Common Plural Nouns (NNS) ===
    ("years", &["NNS"]),
    ("days", &["NNS"]),
    ("people", &["NNS", "NN"]),
    ("men", &["NNS"]),
    ("women", &["NNS"]),
    ("children", &["NNS"]),
    ("ways", &["NNS"]),
    ("times", &["NNS", "VBZ"]),
    ("parts", &["NNS"]),
    ("places", &["NNS", "VBZ"]),
    ("cases", &["NNS", "VBZ"]),
    ("weeks", &["NNS"]),
    ("companies", &["NNS"]),
    ("systems", &["NNS"]),
    ("programs", &["NNS", "VBZ"]),
    ("questions", &["NNS"]),
    ("governments", &["NNS"]),
    ("numbers", &["NNS", "VBZ"]),
    ("nights", &["NNS"]),
    ("points", &["NNS", "VBZ"]),
    ("rooms", &["NNS", "VBZ"]),
    ("areas", &["NNS", "VBZ"]),
    ("stories", &["NNS"]),
    ("facts", &["NNS"]),
    ("months", &["NNS"]),
    ("studies", &["NNS", "VBZ"]),
    ("books", &["NNS", "VBZ"]),
    ("jobs", &["NNS"]),
    ("words", &["NNS", "VBZ"]),
    ("businesses", &["NNS"]),
    ("issues", &["NNS", "VBZ"]),
    ("sides", &["NNS", "VBZ"]),
    ("kinds", &["NNS"]),
    ("heads", &["NNS", "VBZ"]),
    ("houses", &["NNS", "VBZ"]),
    ("services", &["NNS"]),
    ("friends", &["NNS"]),
    ("fathers", &["NNS"]),
    ("powers", &["NNS", "VBZ"]),
    ("hours", &["NNS"]),
    ("games", &["NNS", "VBZ"]),
    ("lines", &["NNS", "VBZ"]),
    ("ends", &["NNS", "VBZ"]),
    ("members", &["NNS"]),
    ("laws", &["NNS"]),
    ("cars", &["NNS"]),
    ("cities", &["NNS"]),
    ("communities", &["NNS"]),
    ("names", &["NNS", "VBZ"]),
    ("teams", &["NNS", "VBZ"]),
    ("minutes", &["NNS"]),
    ("ideas", &["NNS"]),
    ("bodies", &["NNS"]),
    ("parents", &["NNS"]),
    ("faces", &["NNS", "VBZ"]),
    ("levels", &["NNS", "VBZ"]),
    ("offices", &["NNS"]),
    ("doors", &["NNS"]),
    ("persons", &["NNS"]),
    ("wars", &["NNS"]),
    ("histories", &["NNS"]),
    ("parties", &["NNS"]),
    ("results", &["NNS", "VBZ"]),
    ("reasons", &["NNS", "VBZ"]),
    ("girls", &["NNS"]),
    ("moments", &["NNS"]),
    ("teachers", &["NNS"]),
    ("forces", &["NNS", "VBZ"]),
    ("feet", &["NNS"]),
    ("boys", &["NNS"]),
    ("ages", &["NNS", "VBZ"]),
    ("policies", &["NNS"]),
    ("processes", &["NNS", "VBZ"]),
    ("markets", &["NNS", "VBZ"]),
    ("products", &["NNS"]),
    ("effects", &["NNS", "VBZ"]),
    ("classes", &["NNS", "VBZ"]),
    ("pieces", &["NNS"]),
    ("rates", &["NNS", "VBZ"]),
    ("roles", &["NNS"]),
    ("degrees", &["NNS"]),
    ("projects", &["NNS", "VBZ"]),
    ("records", &["NNS", "VBZ"]),
    ("stages", &["NNS", "VBZ"]),
    ("figures", &["NNS", "VBZ"]),
    ("tables", &["NNS", "VBZ"]),
    ("fields", &["NNS", "VBZ"]),
    ("terms", &["NNS", "VBZ"]),
    ("pictures", &["NNS", "VBZ"]),
    ("values", &["NNS", "VBZ"]),
    ("models", &["NNS", "VBZ"]),
    ("sources", &["NNS", "VBZ"]),
    ("groups", &["NNS", "VBZ"]),
    ("problems", &["NNS"]),
    ("events", &["NNS"]),
    ("activities", &["NNS"]),
    ("countries", &["NNS"]),
    ("structures", &["NNS", "VBZ"]),
    ("plans", &["NNS", "VBZ"]),
    ("forms", &["NNS", "VBZ"]),
    ("views", &["NNS", "VBZ"]),
    ("nations", &["NNS"]),
    ("families", &["NNS"]),
    ("chances", &["NNS", "VBZ"]),
    ("choices", &["NNS"]),
    ("actions", &["NNS"]),
    ("responses", &["NNS"]),
    ("examples", &["NNS"]),
    ("voices", &["NNS", "VBZ"]),
    ("types", &["NNS", "VBZ"]),
    ("materials", &["NNS"]),
    ("features", &["NNS", "VBZ"]),
    ("students", &["NNS"]),
    ("doctors", &["NNS"]),
    ("professors", &["NNS"]),
    ("papers", &["NNS", "VBZ"]),
    ("tests", &["NNS", "VBZ"]),
    ("rules", &["NNS", "VBZ"]),
    ("sentences", &["NNS"]),
    ("languages", &["NNS"]),
    ("texts", &["NNS", "VBZ"]),
    ("letters", &["NNS"]),
    ("pages", &["NNS", "VBZ"]),
    ("chapters", &["NNS"]),
    ("sections", &["NNS"]),
    ("titles", &["NNS", "VBZ"]),
    ("patterns", &["NNS"]),
    ("files", &["NNS", "VBZ"]),
    ("codes", &["NNS", "VBZ"]),
    ("errors", &["NNS"]),
    ("versions", &["NNS"]),
    ("methods", &["NNS"]),
    ("functions", &["NNS"]),
    ("steps", &["NNS", "VBZ"]),
    ("conditions", &["NNS"]),
    ("tasks", &["NNS"]),
    ("efforts", &["NNS"]),
    ("computers", &["NNS"]),
    ("machines", &["NNS"]),
    ("tools", &["NNS"]),
    ("devices", &["NNS"]),
    ("reasons", &["NNS"]),
    ("reports", &["NNS", "VBZ"]),
    ("decisions", &["NNS"]),
    ("suggestions", &["NNS"]),
    ("differences", &["NNS"]),
    ("relationships", &["NNS"]),
    ("communities", &["NNS"]),
    ("discussions", &["NNS"]),
    ("solutions", &["NNS"]),
    ("options", &["NNS"]),
    ("opportunities", &["NNS"]),
    ("resources", &["NNS"]),
    ("challenges", &["NNS", "VBZ"]),
    ("benefits", &["NNS", "VBZ"]),
    ("skills", &["NNS"]),
    ("views", &["NNS", "VBZ"]),
    ("opinions", &["NNS"]),
    ("comments", &["NNS"]),
    ("criticisms", &["NNS"]),
    ("analyses", &["NNS"]),
    ("theories", &["NNS"]),
    ("measures", &["NNS", "VBZ"]),
    ("standards", &["NNS"]),
    ("natures", &["NNS"]),
    ("environments", &["NNS"]),
    ("populations", &["NNS"]),
    ("centuries", &["NNS"]),
    ("decades", &["NNS"]),
    ("seasons", &["NNS"]),
    ("things", &["NNS"]),
    ("others", &["NNS"]),
    ("many", &["NNS", "DT", "JJ"]),
    ("some", &["DT"]),
    ("those", &["DT"]),

    // === Common Adjectives (JJ) ===
    ("good", &["JJ"]),
    ("new", &["JJ"]),
    ("first", &["JJ", "CD", "RB"]),
    ("last", &["JJ", "RB"]),
    ("long", &["JJ", "RB", "VB"]),
    ("great", &["JJ"]),
    ("little", &["JJ", "RB"]),
    ("own", &["JJ"]),
    ("other", &["JJ"]),
    ("old", &["JJ"]),
    ("right", &["JJ", "RB", "NN"]),
    ("big", &["JJ"]),
    ("high", &["JJ", "RB"]),
    ("different", &["JJ"]),
    ("small", &["JJ"]),
    ("large", &["JJ"]),
    ("next", &["JJ", "RB"]),
    ("early", &["JJ", "RB"]),
    ("young", &["JJ"]),
    ("important", &["JJ"]),
    ("few", &["JJ", "DT"]),
    ("public", &["JJ", "NN"]),
    ("bad", &["JJ"]),
    ("same", &["JJ"]),
    ("quick", &["JJ", "RB"]),
    ("able", &["JJ"]),
    ("free", &["JJ", "RB", "VB"]),
    ("sure", &["JJ", "RB"]),
    ("strong", &["JJ"]),
    ("possible", &["JJ"]),
    ("whole", &["JJ", "NN"]),
    ("special", &["JJ"]),
    ("hard", &["JJ", "RB"]),
    ("real", &["JJ", "RB"]),
    ("best", &["JJS", "RB"]),
    ("clear", &["JJ", "RB", "VB"]),
    ("recent", &["JJ"]),
    ("certain", &["JJ"]),
    ("personal", &["JJ"]),
    ("full", &["JJ"]),
    ("dark", &["JJ", "NN"]),
    ("simple", &["JJ"]),
    ("easy", &["JJ", "RB"]),
    ("final", &["JJ"]),
    ("main", &["JJ"]),
    ("past", &["JJ", "NN", "RB", "IN"]),
    ("local", &["JJ"]),
    ("major", &["JJ", "NN"]),
    ("short", &["JJ", "RB"]),
    ("natural", &["JJ"]),
    ("ready", &["JJ"]),
    ("complete", &["JJ", "VB"]),
    ("beautiful", &["JJ"]),
    ("necessary", &["JJ"]),
    ("available", &["JJ"]),
    ("general", &["JJ", "NN"]),
    ("happy", &["JJ"]),
    ("serious", &["JJ"]),
    ("economic", &["JJ"]),
    ("political", &["JJ"]),
    ("social", &["JJ"]),
    ("international", &["JJ"]),
    ("human", &["JJ", "NN"]),
    ("common", &["JJ"]),
    ("single", &["JJ"]),
    ("medical", &["JJ"]),
    ("current", &["JJ", "NN"]),
    ("wrong", &["JJ", "RB", "NN"]),
    ("private", &["JJ"]),
    ("foreign", &["JJ"]),
    ("fine", &["JJ", "RB", "NN"]),
    ("environmental", &["JJ"]),
    ("financial", &["JJ"]),
    ("blue", &["JJ", "NN"]),
    ("democratic", &["JJ"]),
    ("various", &["JJ"]),
    ("entire", &["JJ"]),
    ("close", &["JJ", "RB", "VB"]),
    ("legal", &["JJ"]),
    ("religious", &["JJ"]),
    ("cold", &["JJ", "NN"]),
    ("green", &["JJ", "NN"]),
    ("nice", &["JJ"]),
    ("huge", &["JJ"]),
    ("popular", &["JJ"]),
    ("traditional", &["JJ"]),
    ("cultural", &["JJ"]),
    ("possible", &["JJ"]),
    ("basic", &["JJ"]),
    ("specific", &["JJ"]),
    ("positive", &["JJ"]),
    ("negative", &["JJ"]),
    ("national", &["JJ"]),
    ("western", &["JJ"]),
    ("southern", &["JJ"]),
    ("northern", &["JJ"]),
    ("eastern", &["JJ"]),
    ("central", &["JJ"]),
    ("modern", &["JJ"]),
    ("ancient", &["JJ"]),
    ("original", &["JJ"]),
    ("normal", &["JJ", "NN"]),
    ("original", &["JJ"]),
    ("particular", &["JJ"]),
    ("similar", &["JJ"]),
    ("proper", &["JJ"]),
    ("actual", &["JJ"]),
    ("potential", &["JJ", "NN"]),
    ("significant", &["JJ"]),
    ("obvious", &["JJ"]),
    ("appropriate", &["JJ"]),
    ("effective", &["JJ"]),
    ("essential", &["JJ"]),
    ("practical", &["JJ"]),
    ("reasonable", &["JJ"]),
    ("responsible", &["JJ"]),
    ("successful", &["JJ"]),
    ("total", &["JJ", "NN"]),
    ("true", &["JJ", "RB"]),
    ("usual", &["JJ"]),
    ("white", &["JJ", "NN"]),
    ("black", &["JJ", "NN"]),
    ("red", &["JJ", "NN"]),
    ("hot", &["JJ"]),
    ("warm", &["JJ", "VB"]),
    ("cool", &["JJ", "VB"]),
    ("rich", &["JJ"]),
    ("poor", &["JJ"]),
    ("deep", &["JJ", "RB"]),
    ("wide", &["JJ", "RB"]),
    ("narrow", &["JJ"]),
    ("heavy", &["JJ"]),
    ("light", &["JJ", "NN", "VB"]),
    ("soft", &["JJ"]),
    ("sharp", &["JJ"]),
    ("smooth", &["JJ"]),
    ("straight", &["JJ", "RB"]),
    ("thick", &["JJ"]),
    ("thin", &["JJ", "VB"]),
    ("bright", &["JJ"]),
    ("quiet", &["JJ", "RB"]),
    ("slow", &["JJ", "VB"]),
    ("fast", &["JJ", "RB"]),
    ("safe", &["JJ"]),
    ("clean", &["JJ", "VB"]),
    ("fresh", &["JJ"]),
    ("gray", &["JJ", "NN"]),
    ("grey", &["JJ", "NN"]),
    ("yellow", &["JJ", "NN"]),
    ("brown", &["JJ", "NN"]),
    ("pink", &["JJ", "NN"]),
    ("silver", &["JJ", "NN"]),
    ("golden", &["JJ"]),
    ("empty", &["JJ"]),
    ("dry", &["JJ", "VB"]),
    ("flat", &["JJ", "NN"]),
    ("round", &["JJ", "NN", "VB"]),
    ("square", &["JJ", "NN"]),
    ("wild", &["JJ"]),
    ("sweet", &["JJ"]),
    ("certain", &["JJ"]),
    ("frequent", &["JJ"]),
    ("daily", &["JJ", "RB"]),
    ("weekly", &["JJ", "RB"]),
    ("monthly", &["JJ", "RB"]),
    ("annual", &["JJ"]),
    ("annual", &["JJ"]),
    ("tiny", &["JJ"]),
    ("vast", &["JJ"]),
    ("broad", &["JJ"]),
    ("narrow", &["JJ"]),
    ("upper", &["JJ"]),
    ("lower", &["JJ"]),
    ("inner", &["JJ"]),
    ("outer", &["JJ"]),
    ("latter", &["JJ"]),
    ("former", &["JJ"]),
    ("supreme", &["JJ"]),
    ("average", &["JJ", "NN"]),
    ("ordinary", &["JJ"]),
    ("extreme", &["JJ", "NN"]),
    ("critical", &["JJ"]),
    ("crucial", &["JJ"]),
    ("vital", &["JJ"]),
    ("severe", &["JJ"]),
    ("separate", &["JJ", "VB"]),
    ("independent", &["JJ"]),
    ("individual", &["JJ", "NN"]),
    ("standard", &["JJ", "NN"]),
    ("official", &["JJ", "NN"]),
    ("military", &["JJ", "NN"]),
    ("urban", &["JJ"]),
    ("rural", &["JJ"]),
    ("digital", &["JJ"]),
    ("virtual", &["JJ"]),
    ("classic", &["JJ", "NN"]),
    ("typical", &["JJ"]),
    ("unique", &["JJ"]),
    ("familiar", &["JJ"]),
    ("obvious", &["JJ"]),
    ("ordinary", &["JJ"]),
    ("constant", &["JJ", "NN"]),
    ("complex", &["JJ", "NN"]),
    ("scientific", &["JJ"]),
    ("professional", &["JJ", "NN"]),
    ("technical", &["JJ"]),
    ("creative", &["JJ"]),
    ("likely", &["JJ", "RB"]),
    ("unlikely", &["JJ", "RB"]),
    ("unable", &["JJ"]),
    ("aware", &["JJ"]),
    ("unable", &["JJ"]),

    // === Comparative Adjectives (JJR) ===
    ("better", &["JJR", "RBR"]),
    ("worse", &["JJR", "RBR"]),
    ("bigger", &["JJR"]),
    ("smaller", &["JJR"]),
    ("older", &["JJR"]),
    ("younger", &["JJR"]),
    ("faster", &["JJR", "RBR"]),
    ("slower", &["JJR"]),
    ("higher", &["JJR", "RBR"]),
    ("lower", &["JJR", "RBR"]),
    ("longer", &["JJR", "RBR"]),
    ("shorter", &["JJR"]),
    ("easier", &["JJR"]),
    ("harder", &["JJR", "RBR"]),
    ("newer", &["JJR"]),
    ("stronger", &["JJR"]),
    ("weaker", &["JJR"]),
    ("greater", &["JJR"]),
    ("larger", &["JJR"]),
    ("quieter", &["JJR"]),
    ("cleaner", &["JJR"]),
    ("cheaper", &["JJR"]),
    ("richer", &["JJR"]),
    ("poorer", &["JJR"]),
    ("deeper", &["JJR"]),
    ("wider", &["JJR"]),
    ("broader", &["JJR"]),
    ("heavier", &["JJR"]),
    ("lighter", &["JJR"]),
    ("thinner", &["JJR"]),
    ("thicker", &["JJR"]),
    ("brighter", &["JJR"]),
    ("darker", &["JJR"]),
    ("warmer", &["JJR"]),
    ("cooler", &["JJR"]),
    ("hotter", &["JJR"]),
    ("colder", &["JJR"]),
    ("simpler", &["JJR"]),
    ("closer", &["JJR", "RBR"]),
    ("earlier", &["JJR", "RBR"]),
    ("later", &["JJR", "RBR"]),
    ("further", &["JJR", "RBR"]),
    ("farther", &["JJR", "RBR"]),

    // === Superlative Adjectives (JJS) ===
    ("best", &["JJS", "RBS"]),
    ("worst", &["JJS", "RBS"]),
    ("biggest", &["JJS"]),
    ("smallest", &["JJS"]),
    ("oldest", &["JJS"]),
    ("youngest", &["JJS"]),
    ("fastest", &["JJS", "RBS"]),
    ("slowest", &["JJS"]),
    ("highest", &["JJS", "RBS"]),
    ("lowest", &["JJS", "RBS"]),
    ("longest", &["JJS"]),
    ("shortest", &["JJS"]),
    ("easiest", &["JJS"]),
    ("hardest", &["JJS", "RBS"]),
    ("newest", &["JJS"]),
    ("strongest", &["JJS"]),
    ("weakest", &["JJS"]),
    ("greatest", &["JJS"]),
    ("largest", &["JJS"]),
    ("latest", &["JJS"]),
    ("earliest", &["JJS"]),
    ("closest", &["JJS"]),
    ("simplest", &["JJS"]),
    ("richest", &["JJS"]),
    ("poorest", &["JJS"]),
    ("deepest", &["JJS"]),
    ("widest", &["JJS"]),
    ("brightest", &["JJS"]),
    ("darkest", &["JJS"]),
    ("warmest", &["JJS"]),
    ("coolest", &["JJS"]),
    ("hottest", &["JJS"]),
    ("coldest", &["JJS"]),

    // === Cardinal Numbers (CD) ===
    ("one", &["CD", "NN"]),
    ("two", &["CD", "NN"]),
    ("three", &["CD"]),
    ("four", &["CD"]),
    ("five", &["CD", "NN"]),
    ("six", &["CD", "NN"]),
    ("seven", &["CD"]),
    ("eight", &["CD", "NN"]),
    ("nine", &["CD"]),
    ("ten", &["CD", "NN"]),
    ("eleven", &["CD"]),
    ("twelve", &["CD"]),
    ("thirteen", &["CD"]),
    ("fourteen", &["CD"]),
    ("fifteen", &["CD"]),
    ("sixteen", &["CD"]),
    ("seventeen", &["CD"]),
    ("eighteen", &["CD"]),
    ("nineteen", &["CD"]),
    ("twenty", &["CD", "NN"]),
    ("thirty", &["CD"]),
    ("forty", &["CD"]),
    ("fifty", &["CD"]),
    ("sixty", &["CD"]),
    ("seventy", &["CD"]),
    ("eighty", &["CD"]),
    ("ninety", &["CD"]),
    ("hundred", &["CD", "NN", "JJ"]),
    ("thousand", &["CD", "NN"]),
    ("million", &["CD", "NN"]),
    ("billion", &["CD", "NN"]),
    ("trillion", &["CD", "NN"]),
    ("zero", &["CD", "NN"]),
    ("first", &["ORD", "JJ", "RB"]),
    ("second", &["ORD", "JJ", "NN", "RB"]),
    ("third", &["ORD", "JJ"]),
    ("fourth", &["ORD", "JJ"]),
    ("fifth", &["ORD", "JJ"]),
    ("sixth", &["ORD", "JJ"]),
    ("seventh", &["ORD", "JJ"]),
    ("eighth", &["ORD", "JJ"]),
    ("ninth", &["ORD", "JJ"]),
    ("tenth", &["ORD", "JJ"]),
    ("both", &["DT", "CC"]),

    // === Proper Nouns (NNP) - common ones ===
    ("january", &["NNP"]),
    ("february", &["NNP"]),
    ("march", &["NNP", "NN", "VB"]),
    ("april", &["NNP"]),
    ("may", &["NNP", "MD"]),
    ("june", &["NNP"]),
    ("july", &["NNP"]),
    ("august", &["NNP", "JJ"]),
    ("september", &["NNP"]),
    ("october", &["NNP"]),
    ("november", &["NNP"]),
    ("december", &["NNP"]),
    ("monday", &["NNP"]),
    ("tuesday", &["NNP"]),
    ("wednesday", &["NNP"]),
    ("thursday", &["NNP"]),
    ("friday", &["NNP"]),
    ("saturday", &["NNP"]),
    ("sunday", &["NNP"]),
    ("america", &["NNP"]),
    ("american", &["NNP", "JJ"]),
    ("england", &["NNP"]),
    ("english", &["NNP", "JJ"]),
    ("france", &["NNP"]),
    ("french", &["NNP", "JJ"]),
    ("germany", &["NNP"]),
    ("german", &["NNP", "JJ"]),
    ("italy", &["NNP"]),
    ("italian", &["NNP", "JJ"]),
    ("spain", &["NNP"]),
    ("spanish", &["NNP", "JJ"]),
    ("europe", &["NNP"]),
    ("european", &["NNP", "JJ"]),
    ("asia", &["NNP"]),
    ("asian", &["NNP", "JJ"]),
    ("africa", &["NNP"]),
    ("african", &["NNP", "JJ"]),
    ("china", &["NNP"]),
    ("chinese", &["NNP", "JJ"]),
    ("japan", &["NNP"]),
    ("japanese", &["NNP", "JJ"]),
    ("india", &["NNP"]),
    ("indian", &["NNP", "JJ"]),
    ("russia", &["NNP"]),
    ("russian", &["NNP", "JJ"]),
    ("australia", &["NNP"]),
    ("australian", &["NNP", "JJ"]),
    ("canada", &["NNP"]),
    ("canadian", &["NNP", "JJ"]),
    ("mexico", &["NNP"]),
    ("mexican", &["NNP", "JJ"]),
    ("brazil", &["NNP"]),
    ("brazilian", &["NNP", "JJ"]),
    ("britain", &["NNP"]),
    ("british", &["NNP", "JJ"]),
    ("london", &["NNP"]),
    ("paris", &["NNP"]),
    ("berlin", &["NNP"]),
    ("rome", &["NNP"]),
    ("washington", &["NNP"]),
    ("new york", &["NNP"]),
    ("york", &["NNP"]),
    ("los angeles", &["NNP"]),
    ("chicago", &["NNP"]),
    ("boston", &["NNP"]),
    ("christmas", &["NNP"]),
    ("easter", &["NNP"]),
    ("thanksgiving", &["NNP"]),
    ("halloween", &["NNP"]),
    ("god", &["NNP"]),
    ("jesus", &["NNP"]),
    ("christ", &["NNP"]),
    ("allah", &["NNP"]),
    ("buddha", &["NNP"]),
    ("muhammad", &["NNP"]),
    ("moses", &["NNP"]),
    ("earth", &["NNP", "NN"]),
    ("sun", &["NNP", "NN"]),
    ("moon", &["NNP", "NN"]),
    ("mars", &["NNP", "NN"]),
    ("jupiter", &["NNP"]),
    ("saturn", &["NNP"]),
    ("venus", &["NNP"]),
    ("atlantic", &["NNP", "JJ"]),
    ("pacific", &["NNP", "JJ"]),
    ("christian", &["NNP", "JJ"]),
    ("christianity", &["NNP"]),
    ("islam", &["NNP"]),
    ("muslim", &["NNP", "JJ"]),
    ("judaism", &["NNP"]),
    ("jewish", &["NNP", "JJ"]),
    ("catholic", &["NNP", "JJ"]),
    ("protestant", &["NNP", "JJ"]),
    ("republican", &["NNP", "JJ", "NN"]),
    ("democrat", &["NNP", "NN"]),
    ("congress", &["NNP"]),
    ("senate", &["NNP", "NN"]),
    ("supreme court", &["NNP"]),
    ("white house", &["NNP"]),

    // === Interjections (UH) ===
    ("oh", &["UH"]),
    ("please", &["UH", "VB"]),
    ("thanks", &["UH", "NNS", "VBZ"]),
    ("yes", &["UH", "RB"]),
    ("no", &["UH", "RB", "DT"]),
    ("okay", &["UH", "RB", "JJ"]),
    ("ok", &["UH", "RB", "JJ"]),
    ("hey", &["UH"]),
    ("hi", &["UH"]),
    ("hello", &["UH", "NN"]),
    ("bye", &["UH", "NN"]),
    ("wow", &["UH"]),
    ("oops", &["UH"]),
    ("ah", &["UH"]),
    ("hmm", &["UH"]),
    ("uh", &["UH"]),
    ("um", &["UH"]),
];
